-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 09, 2023 at 07:46 PM
-- Server version: 8.0.31
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+05:30";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `autorealm`
--

-- --------------------------------------------------------

--
-- Table structure for table `admittingreport`
--

CREATE TABLE `admittingreport` (
                                   `report_no` int NOT NULL,
                                   `vehicle_reg_no` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `mileage` int NOT NULL,
                                   `current_fuel_level` enum('full','empty','half','3/4','1/4') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `admitting_time` time NOT NULL,
                                   `departing_time` time NOT NULL,
                                   `windshield` enum('good','scratched','cracked','damaged') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `lights_lf` enum('good','scratched','cracked','damaged','not working') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `light_lf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `lights_rf` enum('good','scratched','cracked','damaged','not working') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `light_rf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `lights_lr` enum('good','scratched','cracked','damaged','not working') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `lights_rr` enum('good','scratched','cracked','damaged','not working') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `toolkit` enum('have','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `sparewheel` enum('have','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_lf` enum('good','scratched','cracked','damaged','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_rf` enum('good','scratched','cracked','damaged','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_lr` enum('good','scratched','cracked','damaged','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_rr` enum('good','scratched','cracked','damaged','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `seat_lf` enum('good','worn','burnholes','torn','stained') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `seat_rf` enum('good','worn','burnholes','torn','stained') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `seat_rear` enum('good','worn','burnholes','torn','stained') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `carpet_lf` enum('good','worn','burnholes','torn','stained','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `carpet_rf` enum('good','worn','burnholes','torn','stained','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `carpet_rear` enum('good','worn','burnholes','torn','stained','missing') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `dashboard` enum('good','scratched','damaged','burnt','stained') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `customer_belongings` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `additional_note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `validated_by` int DEFAULT NULL,
                                   `employee_id` int NOT NULL,
                                   `light_lr_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `light_rr_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `seat_lf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `seat_rf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `seat_rear_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `carpet_lf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `carpet_rf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `carpet_rear_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_lf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_rf_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_lr_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `current_fuel_level_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `dashboard_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `windshield_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `rim_rr_description` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `admitting_date` date NOT NULL,
                                   `is_approved` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admittingreport`
--

INSERT INTO `admittingreport` (`report_no`, `vehicle_reg_no`, `mileage`, `current_fuel_level`, `admitting_time`, `departing_time`, `windshield`, `lights_lf`, `light_lf_description`, `lights_rf`, `light_rf_description`, `lights_lr`, `lights_rr`, `toolkit`, `sparewheel`, `rim_lf`, `rim_rf`, `rim_lr`, `rim_rr`, `seat_lf`, `seat_rf`, `seat_rear`, `carpet_lf`, `carpet_rf`, `carpet_rear`, `dashboard`, `customer_belongings`, `additional_note`, `validated_by`, `employee_id`, `light_lr_description`, `light_rr_description`, `seat_lf_description`, `seat_rf_description`, `seat_rear_description`, `carpet_lf_description`, `carpet_rf_description`, `carpet_rear_description`, `rim_lf_description`, `rim_rf_description`, `rim_lr_description`, `current_fuel_level_description`, `dashboard_description`, `windshield_description`, `rim_rr_description`, `admitting_date`, `is_approved`) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (15, 'WP kw 34245', 112, 'full', '00:00:00', '18:49:27', 'good', 'cracked', 'cfvgbh', 'good', 'cfvgbh', 'damaged', 'not working', 'missing', 'have', 'good', 'scratched', 'cracked', 'damaged', 'stained', 'torn', 'burnholes', 'worn', 'good', 'burnholes', 'scratched', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, 'tfdc', 'jhbg', 'rth', ',kmjnhg', 'cvbn', 'ujm', 'okjn', 'rghj', 'vbn', 'ftghnj', 'ijhb', 'oijhbvbnm', 'tgyhjxcf', 'cfvg', 'fvgbhjn', '2023-05-08', 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (16, 'BIU 4561', 112, 'empty', '00:00:00', '18:42:41', 'good', 'scratched', '', 'scratched', '', 'good', 'scratched', 'have', 'have', 'scratched', 'scratched', 'scratched', 'good', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-07', 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (17, 'ttt', 112, 'half', '00:00:00', '00:00:00', 'good', 'cracked', '', 'cracked', '', 'good', 'cracked', 'have', 'have', 'cracked', 'cracked', 'cracked', 'good', 'burnholes', 'burnholes', 'burnholes', 'burnholes', 'burnholes', 'burnholes', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-05', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (18, 'ttt', 112, '3/4', '00:00:00', '00:00:00', 'good', 'damaged', '', 'damaged', '', 'good', 'damaged', 'have', 'have', 'damaged', 'damaged', 'damaged', 'good', 'torn', 'torn', 'torn', 'torn', 'torn', 'torn', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-03-13', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (19, 'ttt', 112, '3/4', '00:00:00', '00:00:00', 'cracked', 'not working', '', 'not working', '', 'good', 'not working', 'have', 'have', 'missing', 'missing', 'missing', 'good', 'stained', 'stained', 'stained', 'stained', 'stained', 'stained', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-04-03', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (20, 'ttt', 112, '3/4', '00:00:00', '00:00:00', 'damaged', 'not working', '', 'not working', '', 'good', 'not working', 'have', 'missing', 'missing', 'missing', 'missing', 'good', 'stained', 'stained', 'stained', 'stained', 'stained', 'stained', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-01-10', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (21, 'ttt', 112, '3/4', '00:00:00', '00:00:00', 'damaged', 'cracked', '', 'not working', '', 'good', 'scratched', 'have', 'missing', 'missing', 'missing', 'missing', 'good', 'worn', 'burnholes', 'stained', 'stained', 'stained', 'stained', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-05', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (22, 'ttt', 112, '3/4', '00:00:00', '00:00:00', 'damaged', 'cracked', '', 'not working', '', 'good', 'scratched', 'have', 'missing', 'missing', 'missing', 'missing', 'good', 'worn', 'burnholes', 'stained', 'worn', 'stained', 'good', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2022-12-12', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (23, '123456789', 112, '3/4', '00:00:00', '00:00:00', 'damaged', 'cracked', '', 'not working', '', 'good', 'scratched', 'have', 'missing', 'damaged', 'missing', 'cracked', 'good', 'worn', 'burnholes', 'stained', 'worn', 'stained', 'good', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-24', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (24, 'ttt', 112, '3/4', '00:00:00', '00:00:00', 'scratched', 'scratched', '', 'cracked', '', 'good', 'not working', 'missing', 'have', 'damaged', 'missing', 'cracked', 'good', 'worn', 'burnholes', 'stained', 'torn', 'stained', 'worn', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-09', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (25, 'ttt', 112, '1/4', '00:00:00', '00:00:00', 'scratched', 'scratched', '', 'cracked', '', 'good', 'not working', 'missing', 'have', 'damaged', 'missing', 'cracked', 'good', 'worn', 'burnholes', 'stained', 'torn', 'stained', 'worn', '', '                         &#13;&#10;qn                    ', '                         &#13;&#10;                    mm', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-08', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (26, 'dfghjkl', 44, 'empty', '00:00:00', '00:00:00', 'scratched', 'scratched', '', 'not working', '', 'good', 'cracked', 'missing', 'have', 'scratched', 'cracked', 'damaged', 'good', 'worn', 'burnholes', 'torn', 'missing', 'torn', 'stained', '', '                         &#13;&#10;fcrc                    ', '                         &#13;&#10;   rfct                 ', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-02-08', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (27, 'dfghjkl', 44, 'empty', '00:00:00', '00:00:00', 'scratched', 'scratched', '', 'not working', '', 'good', 'cracked', 'missing', 'have', 'scratched', 'cracked', 'damaged', 'good', 'worn', 'burnholes', 'torn', 'missing', 'torn', 'stained', 'burnt', '                         &#13;&#10;fcrc                    ', '                         &#13;&#10;   rfct                 ', NULL, 17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-03', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (28, 'NT 234', 1234, 'full', '13:34:00', '00:00:00', 'good', 'good', '', 'good', '', 'good', 'good', 'have', 'have', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', '                         &#13;&#10;                    ', '                         &#13;&#10;                    ', NULL, 11, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-09', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (29, 'xcrtfvygbun', 999, 'full', '15:34:00', '12:02:14', 'good', 'good', '', 'good', '', 'good', 'good', 'have', 'have', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', '                         &#13;&#10;                    ', '                         &#13;&#10;                    ', NULL, 11, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-05-09', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admittingreport`
--
ALTER TABLE `admittingreport`
    ADD PRIMARY KEY (`report_no`),
    ADD KEY `created by` (`employee_id`),
    ADD KEY `validated by` (`validated_by`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admittingreport`
--
ALTER TABLE `admittingreport`
    MODIFY `report_no` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `admittingreport`
--
ALTER TABLE `admittingreport`
    ADD CONSTRAINT `created by` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`),
    ADD CONSTRAINT `validated by` FOREIGN KEY (`validated_by`) REFERENCES `employee` (`employee_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
